/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.module;

import org.apache.commons.httpclient.HttpClient;
import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Connector;
import org.mule.api.annotations.Processor;
import org.mule.api.annotations.rest.*;

import java.io.IOException;

/**
 * Cloud Connector
 *
 * @author MuleSoft, Inc.
 */
@Connector(name="espn", schemaVersion="1.0-SNAPSHOT")
public abstract class espnConnector
{
    public static final String BASE_URI = "http://api.espn.com/v1";
    public static final String MLB_RESOURCE = "/sports/baseball/mlb";


    @RestHttpClient
    private HttpClient httpClient;

    /**
     * Configurable
     */
    @Configurable
    @RestUriParam("apiKey")
    private String apiKey;


    public espnConnector()
    {
        httpClient = new HttpClient();
    }

    /**
     * Set property
     *
     * @param apiKey - ESPN API key (see developer.espn.com for access to their APIs)
     */
    public void setApiKey(String apiKey)
    {
        this.apiKey = apiKey;
    }

    public String getApiKey()
    {
        return this.apiKey;
    }

    /**
     * Set property
     *
     * @param httpClient
     */

    public void setHttpClient(HttpClient httpClient){
        this.httpClient = httpClient;
    }

    public HttpClient getHttpClient(){
        return this.httpClient;
    }

    /**
     * getListBaseballAthletes
     *
     * {@sample.xml ../../../doc/espn-connector.xml.sample espn:get-list-baseball-athletes}
     *
     * @return String - JSON string representing MLB athletes
     * @throws IOException
     *
     */
    @Processor
    @RestCall(uri = BASE_URI + MLB_RESOURCE + "/athletes?apikey={apiKey}", method = HttpMethod.GET)
    public abstract String getListBaseballAthletes() throws IOException;

    /**
     * getBaseballAthlete
     *
     * {@sample.xml ../../../doc/espn-connector.xml.sample espn:get-baseball-athlete}
     *
     * @param playerId - ESPN player id
     * @return String - JSON string representing a particular MLB athletes
     * @throws IOException
     *
     */
    @Processor
    @RestCall(uri = BASE_URI + MLB_RESOURCE + "/athletes/{id}?apikey={apiKey}", method = HttpMethod.GET)
    public abstract String getBaseballAthlete(@RestUriParam("id") String playerId) throws IOException;


}
